server:
  port: 8082

spring:
  application:
    name: charactersheet
  datasource:
    password: pd
    url: jdbc:postgresql://localhost:5432/charactersheet
    username: pd
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
project-d:
  integrations:
    rule-book:
      base-url: http://localhost:8081
      rooms-url: /api/rooms
      room-rules-url: /api/rooms/{0}/rules
      races-url: /api/races
      classes-url: /api/classes
      abilities-url: /api/abilities
      skills-url: /api/skills
      skills-by-code-url: /api/skills/byCode
      skills-by-class-url: /api/skills/byClass
    itemstorage:
      api-url: api
      base-url: http://localhost:8083
      inventory-url: inventory
      equip-url: equip
      count-url: count
      money-url: money
      items-url: items
      search-url: search
